version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    reviewers:
      - "helmedeiros"
    assignees:
      - "helmedeiros"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group minor and patch updates together
    groups:
      astro-ecosystem:
        patterns:
          - "astro*"
          - "@astrojs/*"
        update-types:
          - "minor"
          - "patch"
      tailwind-ecosystem:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    reviewers:
      - "helmedeiros"
    assignees:
      - "helmedeiros"
    commit-message:
      prefix: "ci"
      include: "scope"
